_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 16
hidden_size:
    value: 128
learning_rate:
    value: 0.002476624276854241
num_layers:
    value: 3
optimizer:
    value: sgd
